config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies
  resources :lists do
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: "successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show

    @list = List.find(params[:id])
    #raise
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end
end

private
def list_params
  params.require(:list).permit(:name)
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/index.html.erb
<div class="container">
<h2>Bookmarks</h2>
<ul class="list-group">
  <%  @list.bookmarks.each do |bookmark| %>
  <li class="list-group-item"><%= bookmark.comment %></li>
  <% end %>
</ul>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
<%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit, class:"btn btn-primary"%>
  </div>

  </div>
<% end %>
</div>

app/views/bookmarks/show.html.erb
<%@list.bookmark.each do  |bookmark|%>
<%@list.bookmark.comment%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
<h2>List</h2>
<ul class="list-group">
  <% @lists.each do |list| %>
  <li class="list-group-item"><%= link_to list.name , list_path(list)%></li>
  <% end %>
</ul>
</div>

app/views/lists/new.html.erb
<div class="container">
<h2>Add New List</h2>
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
<div class="card-trip">
  <% @list.bookmarks.each do |bookmark| %>
  <img src="<%= bookmark.movie.poster_url %>" />
  <div class="card-trip-infos">
    <div>
      <h2><strong>Movie Title : </strong><%= bookmark.movie.title %></h2>
      <p><strong>Reviews : </strong><%= bookmark.comment %></p>
    </div>
  </div>
  <% end %>
</div>
<%= link_to "Add a Review",  new_list_bookmark_path(@list)%>
</div>

app/views/movies/index.html.erb
<div class="container">
<h2>Movie List</h2>
<div class="card-trip">
<% @movies.each do |movie|  %>
  <img src= "<%= movie.poster_url%>" class="img-fluid" />
  <div class="card-movie-infos">
    <div>
      <h2><%= link_to movie.title, movie_path(movie) %></h2>
      <p><%= movie.overview %></p>
      <p><%= movie.rating %></p>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/movies/show.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%= @movie.poster_url%>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= @movie.title %></h5>
    <p class="card-text"><%= @movie.overview %></p>
    <p class="card-text"><%= @movie.rating%></p>
  </div>
</div>